# Generated by Django 4.1 on 2022-12-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task", models.CharField(max_length=120)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("duration", models.DateTimeField(null=True)),
                ("done", models.BooleanField(default=False)),
                ("completed", models.DateTimeField(null=True)),
            ],
        ),
    ]
