# Generated by Django 4.1 on 2022-12-18 11:04

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("demotodoapi", "0002_alter_todo_task"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="todo",
            managers=[
                ("todos", django.db.models.manager.Manager()),
            ],
        ),
    ]
