# Generated by Django 4.1 on 2022-12-18 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("demotodoapi", "0003_alter_todo_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="todo",
            managers=[],
        ),
    ]
