# Generated by Django 4.1 on 2023-01-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demotodoapi", "0007_cart_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(blank=True, default=1, max_length=120),
            preserve_default=False,
        ),
    ]
